[package]
authors = ["Johan Kristell <johan@jott.se>"]
name = "nucleo-f401re"
version = "0.1.1"
description = "Board Support crate for the STM32 NUCLEO-f401RE development board"
repository = "https://github.com/jkristell/nucleo-f401re"
license = "0BSD"
keywords = [
    "arm",
    "cortex-m",
    "template",
]
categories = [
    "embedded",
    "no-std",
]

[dependencies]
cortex-m = "0.5.8"
cortex-m-rt = "0.6.7"

[dependencies.embedded-hal]
features = ["unproven"]
version = "0.2.2"

[dependencies.stm32f4xx-hal]
default-features = false
features = ["rt", "stm32f401"]
version = "0.2.8"

[dev-dependencies]
nb = "0.1.1"
panic-abort = "0.3.0"
hd44780-driver = "0.2.0"

[features]
default = ["rt"]
rt = []

[profile.dev]
debug = true

[profile.release]
debug = true
lto = true
opt-level = "s"
